title: Notes
description: Playground
author: David Cottrell
baseurl: "/notes"
url: "https://cottrell.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-mermaid

markdown: kramdown

sass:
  quiet_deps: true
highlighter: rouge

# Enable MathJax globally
mathjax: true

# Enable Mermaid globally
mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js'

kramdown:
  math_engine: mathjax


github_username: cottrell
# linkedin_username: dcottrell
